### ISSUE TITLE
Missing Feature: iOS Support?

### ISSUE THREAD

**Issue by joeskeen** [NativeScript/nativescript-dev-appium#10]
Looking at the Readme, it states that this is missing iOS support, yet I have been using this with iOS 10 (using the changes from #7).  My question is this: what other things are missing from the iOS support story, or is it to the point that we can change the Readme to show it supports both Android and iOS?

**Comment by hdeshev** [comment]
Last time I checked, the plugin was running on the iOS simulator only. I am not sure if it runs on real iOS devices. Other than that, the README is probably outdated (updating it now for the simulator bit).

**Comment by joeskeen** [comment]
Confirmed: I did try this out just now with a few different configurations and I was unable to get it to run on my iPad device.  Perhaps it is my inexperience with configuring Appium, though, as it seems that Appium itself is capable of running on physical iOS devices.

For now, it may be good to note in the Readme that iOS simulator works, but iOS device support will come later.

**Comment by hdeshev** [comment]
> Perhaps it is my inexperience with configuring Appium, though, as it seems that Appium itself is capable of running on physical iOS devices.

Same here. My guess is that we need to properly build and sign an app for device with the {N} toolchain and Appium should be able to pick it up.

**Comment by SvetoslavTsenov** [comment]
Hey @joeskeen, actually @hdeshev is right. In order to run tests on a real ios device, you need to provide provisioning files. For example I have created a file in e2e/configs folder named xcode.config and include info related to my developer credentials
```
DEVELOPMENT_TEAM=
CODE_SIGN_IDENTITY=iPhone Developer
```
Then you need to provide the file location in appium capabilities file 

```
    "iPhone": {
        "xcodeConfigFile": "/Users/tsenov/git/ns-dev-days-appium-plugin/template-hello-world-ts/e2e/config/xcode.config",
        "showXcodeLog":true,
        "platformName": "iOS",
        "platformVersion": "11.0",
        "deviceName": "BuildUser's iPhone",
        "udid": "1232342342344353"
    }
```
Of course don't miss all requirments described here 
https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md
