### ISSUE TITLE
How to setup a vanilla Javascript project

### ISSUE THREAD

**Issue by endymion00** [NativeScript/nativescript-dev-appium#125]
I have a nativescript project written in vanilla JS and I'm wondering if it is possible to use nativescript-dev-appium.
I added typescript to dev dependencies because no content was generated in e2e folder. After installing it and reinstalling nativescript-dev-appium the sample files were created.
After this I don't know how to proceed.
Is it possible?

**Comment by SvetoslavTsenov** [comment]
Hi @endymion00, sorry for delayed answer. Short answer is yes,
Actually to proceed you need to rewrite typescript tests to javascript. It should look similar to this:

`const { startServer, stopServer } = require("nativescript-dev-appium");
const { createDriver } = require("nativescript-dev-appium");

before("start server", async () => {
    await startServer();
});

after("stop server", async () => {
    await stopServer();
});

describe("sample scenario", () => {
    const defaultWaitTime = 5000;
    let driver;

    before(async () => {
        driver = await createDriver();
    });

    after(async () => {
        await driver.quit();
        console.log("Quit driver!");
    });

    afterEach(async function () {
        if (this.currentTest.state === "failed") {
            await driver.logScreenshot(this.currentTest.title);
        }
    });

    it("should find an element by text", async () => {
        const btnTap = await driver.findElementByText("TAP");
        await btnTap.click();

        const message = "41 taps left";
        const lblMessage = await driver.findElementByText(message);

        // Image verification
        const screen = await driver.compareScreen("hello-world-41");
        assert.isTrue(screen);
    });
});`

After that to execute the tests run this command:

` ./node_modules/.bin/mocha --recursive e2e --timeout 999999 --runType sim.iPhone8 --reuseDevice`

Please make sure you have a device like iPhone8 (it should match device name and apiLevel) that is specified in appium.capabilities.json or change to the one installed on you Mac. The same is valid for android devices. Also I will suggest you to use nativescript-dev-appium@next since it has will be released officially in the next few days and has a few breaking changes.

**Comment by endymion00** [comment]
@SvetoslavTsenov thank your answer :) I will try it!
