### ISSUE TITLE
deviceName seems to be strict check now with 4.0.9

### ISSUE THREAD

**Issue by gkvappium** [NativeScript/nativescript-dev-appium#180]
After upgrading to the latest version of the plugin (4.0.9), looks like there is a strict check for deviceName. We generally use generic phone names (Which is also used for image comparison tests based on the phone name). Not sure why this is a strict check now.

I can use --ignoreDeviceController or give the exact deviceName (Something like SM_G950F). But any reason why this is a strict check now with the latest version of the plugin?

@SvetoslavTsenov , can you please have a look?

**Comment by SvetoslavTsenov** [comment]
This issue is already resolved with next version of the plugin and will be officially published with 5.0.0.
Please have in mind that we are still doing stick check but this time you can use regex to point the 
name or platformVersion of device:
`
"deviceName" : "/iPhone XR/",
"platformVersion": "/12./"
or for android 
"platformVersion": "/8./"
`
