### ISSUE TITLE
Sendkeys not working with hybrid app

### ISSUE THREAD

**Issue by akakira** [NativeScript/nativescript-dev-appium#253]
I have a hybrid application that I am attempting to create a login test for. The application gets focus on the email element but using the findElementByClassName then using the webview element with the sendKeys method results in this exception: 
Error: [element.sendKeys("email@email.com")] Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to 'email@email.com'. Did you interact with the correct element? at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:97) 
Using the AppiumDriver class from nsdevapp, then the driver property I can get the contexts from contexts(), but do not see the context for the webview. Is this expected behavior?

**Comment by akakira** [comment]
I worked with this all day to get the image search function to work, it found the element and actually clicked it but again with sendkeys got this error.
Error: [element.clear()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Method has not yet been implemented
That one is pretty clear, lol!

**Comment by SvetoslavTsenov** [comment]
@akakira, we are going to release a new version 6.1.0 of dev-nappium that will support those scenarios(it is something like a workaround). The problem is related to an issue with `UIAutomator2` and this is not something we can handle. I think @zbranzov  can elaborate more on this! This is the [commit](https://github.com/NativeScript/nativescript-dev-appium/commit/7246bceb7ca1bdedd23da17ab5cee7b03710a5d0) that provides some the ability to send keys via add commands.

**Comment by zbranzov** [comment]
@akakira As Svetoslav mentioned above we have added option to sendKeys method that allows user to input keys via ADB command. This seems to work like a charm on Android and if you have troubles with Android, you can give it a try. Notice that we haven't tested it with Hybrid apps but with Native ones.
