### ISSUE TITLE
Support for Jasmine

### ISSUE THREAD

**Issue by jordandlaman** [NativeScript/nativescript-dev-appium#31]
Getting Jasmine to work with this was pretty hacky due to all the configuration options being set to private.  Would be awesome to have Jasmine2 support for this that is documented.

**Comment by kamok** [comment]
I'm getting this on my NativeScript project when I run `tns build ios`:

```
Executing before-prepare hook from /Users/kamok/code/organizing-mobile/InternalOrganizing/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.7.2
node_modules/@types/jasmine/index.d.ts(14,18): error TS2300: Duplicate identifier 'describe'.

node_modules/@types/jasmine/index.d.ts(16,18): error TS2300: Duplicate identifier 'xdescribe'.

node_modules/@types/jasmine/index.d.ts(25,18): error TS2300: Duplicate identifier 'it'.

node_modules/@types/jasmine/index.d.ts(35,18): error TS2300: Duplicate identifier 'xit'.

node_modules/@types/jasmine/index.d.ts(50,18): error TS2300: Duplicate identifier 'beforeEach'.

node_modules/@types/jasmine/index.d.ts(57,18): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/mocha/index.d.ts(2680,13): error TS2300: Duplicate identifier 'beforeEach'.

node_modules/@types/mocha/index.d.ts(2698,13): error TS2300: Duplicate identifier 'afterEach'.

node_modules/@types/mocha/index.d.ts(2714,13): error TS2300: Duplicate identifier 'describe'.

node_modules/@types/mocha/index.d.ts(2735,13): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/mocha/index.d.ts(2749,13): error TS2300: Duplicate identifier 'it'.

node_modules/@types/mocha/index.d.ts(2770,13): error TS2300: Duplicate identifier 'xit'.
```
Possibly because I use jasmine for unit testing, and trying desperately to use this for e2e testing

**Comment by jordandlaman** [comment]
Looks like you might need to exclude in your tsconfig whichever library you are trying not to use.  Just a guess.

**Comment by bdujrn** [comment]
Support for Jasmine would indeed be awesome.

@jordandlaman So you got nativescript-dev-appium working with Jasmine instead of Mocha? Mind sharing how you set it up?

**Comment by SvetoslavTsenov** [comment]
@Hey, the fix is already publish with the next version of the plugin. 
Please let me know if you still experience some issues.
Have in mind in that installing the plugin for the first time (**if the plugin is not in package.json as devDependency**) you are going to be prompt for a projectType(javascript, typescript, angular, vue, shared-ng-project ) and testsingFramework ( jasmine, mocha, none). In order to skip the interactive terminal it could be provided options as follows:

`npm i -D nativescript-dev-appium@next --projectType= shared-ng-project  --testsingFramework= jasmine `
